### ISSUE TITLE
关于浏览器收藏夹导出的html

### ISSUE THREAD

**Issue by shyu216** [tangxiaoqi-tangxiao/PintreeNewTab#1]
hi，从B站来的，很不错的项目。想问下有打算兼容直接在浏览器收藏夹导出的html吗？谢谢。

**Comment by tangxiaoqi-tangxiao** [comment]
现在就支持这个功能，你直接使用浏览器的导入，插件会同步的

**Comment by PShiYou** [comment]
@tangxiaoqi-tangxiao 下个版本会支持qq登录管理吗（云同步），这样在两台电脑里就可以不会因为标签的不同而烦恼了

**Comment by tangxiaoqi-tangxiao** [comment]
> @tangxiaoqi-tangxiao 下个版本会支持qq登录管理吗（云同步），这样在两台电脑里就可以不会因为标签的不同而烦恼了

嗯，怎么说呢，这个插件就是实时获取你浏览器的书签，浏览器本身是支持云同步的(登录了浏览器的话)
