### ISSUE TITLE
神工具!!!很好用啊

### ISSUE THREAD

**Issue by woeoio** [tangxiaoqi-tangxiao/PintreeNewTab#4]
一直想自己做个能实时操作浏览器书签的工具, 没想到发现了这个 PintreeNewTab

太牛逼了, 

提个建议, 如果能在  extension://mjiogedjmkbihhahaljlefekjbcgplog/index.html
页面操作书签, 但是还差了一个重要功能, 就是: 

新建书签

如果能在这个页面新建书签, 就太方便了, 因为现在浏览器上要收藏网页, 
如果我的目录很多, 那么收藏的时候找目录都要眼瞎了

而  PintreeNewTab 却可以直接搜索出页面, 然后新建 书签( 如果有的话)

**Comment by tangxiaoqi-tangxiao** [comment]
新建书签 我会尝试在最近几天实现
