### ISSUE TITLE
[功能请求]可以设置为新标签页！

### ISSUE THREAD

**Issue by bovindev** [tangxiaoqi-tangxiao/PintreeNewTab#5]
如题，可设置为新标签页
像这样
![file_1730444145829_213](https://github.com/user-attachments/assets/40a7eee5-9dc1-485b-9c52-9ffd267d40fb)

**Comment by bovindev** [comment]
![PixPin_2024-11-01_14-58-22](https://github.com/user-attachments/assets/abd8f227-8ae5-4a77-9e20-56dcd18d1a01)
这个设置开启了也没有任何变化

**Comment by tangxiaoqi-tangxiao** [comment]
你可能被误导了，这个打开新标签页是指，书签是以新标签页的形式打开的

**Comment by tangxiaoqi-tangxiao** [comment]
“打开新标签页”不是将PintreeNewTab设置为新标签页，我之前是有想实现这个功能的，但是如果我没有使用官方提供的设置新标签页的方式，无法上架微软的扩展商店

使用官方设置新标签的方法页无法让用户自定义是不是设置新标签页，如果使用官方的方式，这个插件只要安装就是新标签页，相当于这个扩展就是作为新标签页开发的，可能有人不喜欢这样，所以目前没有好的解决方法

**Comment by tangxiaoqi-tangxiao** [comment]
如果你非常需要这个功能可以更改manifest.json文件
{
  "chrome_url_overrides" : {
    "newtab": "index.html"
  },
}

之后将重新打包一下就行了

**Comment by bovindev** [comment]
> 如果你非常需要这个功能可以更改 manifest.json 文件 { "chrome_url_overrides" : { "newtab": "index.html" }, }
> 
> 之后将重新打包一下就行了

好的，谢谢
